language: python
script: tox
install:
    - pip install tox
    - pip install coveralls
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=py2-cover,py3-cover,coverage
after_success:
  coveralls